---
- name: install
  become: yes
  yum: name=nginx state=latest

- name: start
  become: yes
  service: name=nginx state=started enabled=true

- name: suppression de la conf par defaut
  become: yes
  file: path=/etc/nginx/conf.d/default.conf state=absent
  notify: nginx reload

- name: configuration des sites
  become: yes
  include: site.yml
  with_items: "{{domains}}"

- name: PHP
  become: yes
  include: php.yml

