---
- name: install un repo yum
  become: yes
  yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
   